description = "Ada unit test framework"
name = "aunit"
version = "25.0.0-dev"
authors = ["AdaCore"]
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = ["lib/gnat/aunit.gpr"]
tags=["unit", "test", "unit-test"]

[configuration]
disabled = true

[gpr-externals]
AUNIT_BUILD_MODE = ["Devel", "Install"]
AUNIT_RUNTIME = ["full", "zfp", "zfp-cross", "ravenscar", "ravenscar-cert", "cert"]
